"""empty message

Revision ID: 65feeeb0d88b
Revises: 3c0d86e065c1
Create Date: 2020-04-09 17:51:42.754936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65feeeb0d88b'
down_revision = '3c0d86e065c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
